### ISSUE TITLE
How to implement another operations beyond the basic ones?

### ISSUE THREAD

**Issue by luccasmaso** [facebook/linkbench#26]
Sorry for posting a question like this here. If there is another place better for you let me know.

So, I would like to know if I can achieve more operations beyond the basic ones that implements GraphStore and NodeStore. 

Supose I want to achieve some 3 levels deep traversals, is there some place on the code reserved for these flexibilities? I found on your sigmod paper this phrase: "There are features, such as complex search queries, that cannot be eﬃciently implemented using this interface and are implemented as separate specialized services.". Could you explain what does it mean?

Thanks.

**Comment by timarmstrong** [comment]
You could implement traversals on top of the Linkbench API with multiple calls.  

Some other graph benchmarks focus more on those kind of multi-hop traversals and that has a place but they weren't as relevant for the workload Linkbench was modelling.

When I wrote that sentence about search queries I was alluding to some other backend services Facebook uses for things like Graph Search or text search.  E.g. if you want to efficiently query, say, "people in Chicago named Tim who like Justin Bieber" you need additional indexes and a different query API.

I'm not sure if this is the appropriate place either - I suppose we can take the conversation into email if we want to get more in depth.

**Comment by mdcallag** [comment]
Other products handle more complex query processing. Perhaps we need a few more interns like Tim Armstrong to do awesome work leading to SIGMOD/VLDB/ICDE papers explaining the workload on those systems. Well, it would also help to have public conference papers explaining those systems but that has yet to happen. I am not sure that it is a good idea to have the basic social graph OLTP service try to support more complex queries. That might hurt quality of service (response time, etc). This is an interesting question though.

**Comment by luccasmaso** [comment]
Thanks for the answers! I understand the whole point of the Linkbench. I think the main basic operations and only single hops are a good representation of actual OLTP needs as a whole service. And with this basic operations helps to validate if graph databases are good enough for theses use cases and not only for specific deep traversals.
