### ISSUE TITLE
Where do I have to configure to make results in a (average latency) x (ops/s) graphic?

### ISSUE THREAD

**Issue by luccasmaso** [facebook/linkbench#28]
I would like to present the results in a graph like this, but per operation that Linkbench gives:

![sergey-3](https://cloud.githubusercontent.com/assets/1427231/7891699/2398771a-0625-11e5-9f7f-86b01ce91cc9.jpg) 
(source: http://jaxenter.com/evaluating-nosql-performance-which-database-is-right-for-your-data-107481.html)

Should I make multiple tiers changing the number of total requests on the request phase?
Thanks!

**Comment by mdcallag** [comment]
I don't understand your question. First, the graph you provide looks like YCSB output. Linkbench generates a text file as output.

**Comment by luccasmaso** [comment]
Thanks for the response.

Yes, it is actually a YCSB graph. However, I would like to know if there a way to make a representation like this with Linkbench output. In a single run, Linkbench will give me the latencies and how much mean operations/s were made, right? So, how can I submit Linkbench for another round(s) to check new latencies? I want to make a conclusion like this (from the blog above):

> MongoDB’s latency increased substantially as we increased the workload. At 100 operations per second all the four databases had similar performance. But when the workload reached 1,500 operations per second, MongoDB’s latency increased to 100 milliseconds.

Thanks

**Comment by mdcallag** [comment]
We don't include a script to do that. I have done it in the past via awk & sed

**Comment by maykov** [comment]
You can control number of requests per second per thread in the configuration file. You can also control the number of threads. To get each point on the graph, you will have to run an experiment. This can be automated through scripting. I hope, this answers your question.

**Comment by mdcallag** [comment]
Response time increases when there is saturation in hardware + software.
Maybe MongoDB hit a bottleneck before others.

On Tue, Aug 11, 2015 at 4:47 PM, Alexey Maykov <notifications@github.com>
wrote:

> You can control number of requests per second per thread in the
> configuration file. You can also control the number of threads. To get each
> point on the graph, you will have to run an experiment. This can be
> automated through scripting. I hope, this answers your question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/linkbench/issues/28#issuecomment-130113739>.
>



-- 
Mark Callaghan
mdcallag@gmail.com
