### ISSUE TITLE
Load Phase Latency Stats Have Incorrect Units

### ISSUE THREAD

**Issue by ellitron** [facebook/linkbench#29]
Latency stats reported at the end of the load phase are reported as milliseconds, but the numbers are actually in microseconds.

This is because the calls to latencyStats.recordLatency in LinkBenchLoad and NodeLoader are made with latency times measured in nanoseconds, instead of microseconds as the method requires. The "timetaken" argument needs to be scaled by 1000 to convert from nanoseconds to microseconds.

This bug does not exist in latency reporting for the request phase. Those calls to latencyStats.recordLatency correctly convert from nanoseconds to microseconds before making the call.

**Comment by mdcallag** [comment]
Fixed by https://github.com/facebook/linkbench/pull/30
Thanks for the PR
