### ISSUE TITLE
How to use the MemoryLinkStore

### ISSUE THREAD

**Issue by shijiaxin** [facebook/linkbench#31]
I wish to use Linkbench to test the MemoryLinkStore.
But there is not enough documents to help me to start with it

I just copy the config/LinkConfigMysql.properties to config/myconfig.properties
replace the following 2 lines
linkstore = com.facebook.LinkBench.LinkStoreMysql
nodestore = com.facebook.LinkBench.LinkStoreMysql
with
linkstore = com.facebook.LinkBench.MemoryLinkStore
nodestore = com.facebook.LinkBench.MemoryLinkStore

and use following command to start loading links
./bin/linkbench -c config/myconfig.properties

But it seems that it stucks at loading phase.
I also try to use smaller maxid1, but it still doesn't work.

**Comment by mdcallag** [comment]
Will debug when I return from vacation (June 24).

On Thu, Jun 11, 2015 at 8:35 AM, Shi Jiaxin <notifications@github.com>
wrote:

> I wish to use Linkbench to test the MemoryLinkStore.
> But there is not enough documents to help me to start with it
>
> I just copy the config/LinkConfigMysql.properties to
> config/myconfig.properties
> replace the following 2 lines
> linkstore = com.facebook.LinkBench.LinkStoreMysql
> nodestore = com.facebook.LinkBench.LinkStoreMysql
> with
> linkstore = com.facebook.LinkBench.MemoryLinkStore
> nodestore = com.facebook.LinkBench.MemoryLinkStore
>
> and use following command to start loading links
> ./bin/linkbench -c config/myconfig.properties
>
> But it seems that it stucks at loading phase.
> I also try to use smaller maxid1, but it still doesn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/linkbench/issues/31>.
>



-- 
Mark Callaghan
mdcallag@gmail.com

**Comment by mdcallag** [comment]
Even with a small value for maxid1 there will be many links (id2 values) per link with the default (realistic) configuration. I tried this in the FBWorkload.dat file to have fewer id2 values per link and the memory store load finished faster.

nlinks_func = CONST
# config param that goes along with nlinks_func
nlinks_config = 1
# minimum link count: use 0 or 1 for this
nlinks_default = 1

**Comment by mdcallag** [comment]
this looks better - https://gist.github.com/mdcallag/3025b97c74b7ac592798

**Comment by maykov** [comment]
Let us know, if the issue is not solved yet.
