### ISSUE TITLE
PLEASE add meaningful assertion messages

### ISSUE THREAD

**Issue by jexp** [facebook/linkbench#4]
It is almost impossible to figure out why which tests failed and what they intended to test, please add meaningful messages to all asserts

Also the load tests have weird assserts (e.g. the one with all the request counts combined) that combine soo many things that it is not possible to figure out how to solve the issues.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by maykov** [comment]
I don't think, Tim is working on LinkBench anymore. However, if you still need this, we will happily merge a pull request.
